name: Automated Test for find-lowest-number.py

on: [push]

jobs:
  run-tests:
    name: test1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Run Test Case 1 – Ten Numbers
      run: |
        python3 find_lowest_number.py test_data/test1_input.txt test1_output.txt
        diff test1_output.txt test_data/test1_expected.txt

    - name: Run Test Case 2 – One Number
      run: |
        python3 find_lowest_number.py test_data/test2_input.txt test2_output.txt
        diff test2_output.txt test_data/test2_expected.txt

    - name: Run Test Case 3 – Blank File
      run: |
        python3 find_lowest_number.py test_data/test3_input.txt test3_output.txt
        diff test3_output.txt test_data/test3_expected.txt 
